module.exports = {
  INVESTIGATING_OFFICER: "INVESTIGATING_OFFICER",
  FORENSIC_ANALYST: "FORENSIC_ANALYST",
  PUBLIC_PROSECUTOR: "PUBLIC_PROSECUTOR",
  DEFENCE_ADVOCATE: "DEFENCE_ADVOCATE",
  JUDGE: "JUDGE",
  ADMIN: "ADMIN"
};